version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
      
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - aws sts get-caller-identity
  post_build:
    commands:
      - aws cloudformation create-stack --stack-name test-demo-check --template-body file://pract.yaml --capabilities CAPABILITY_NAMED_IAM
      
