version: 0.2
run-as: root
phases:
    pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - ./test.sh
  post_build:
    commands:
      - echo Build completed on `date`
